application: rognotes
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:

- url: /res
  static_dir: templates/simple/res

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.png
  upload: static/img/favicon.png

- url: /admin/.*
  script: main.py
  login: admin

- url: .*
  script: main.py
