application: sanctum
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:

- url: /res
  static_dir: templates/genesis/res

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/img/favicon.png
  upload: static/img/favicon.png

- url: /admin/.*
  script: sanctum.py
  login: admin

- url: /.*
  script: sanctum.app

libraries:
- name: webapp2
  version: latest
- name: django
  version: "1.2"
